### ISSUE TITLE
Support multipart codecs

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#10]
It will provide `org.synchronoss.cloud:nio-multipart-parser` dependency and the related functional configuration.

**Comment by rbraeunlich** [comment]
Hello @sdeleuze I'd like to help but I'm not sure where to start. Do you know which module I could use as blueprint?

**Comment by rbraeunlich** [comment]
I'm stuck in a dead end. Multipart needs a context created from the current `HttpServletRequest` and I have no idea how I can acquire it while creating the module.
