### ISSUE TITLE
Add logging support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#11]
Functional configuration via support in core or in a dedicated module.

**Comment by sdeleuze** [comment]
@tgirard12 Thanks for the latest improvements.

What do you think about providing a shortcut for `LoggerFactory.getLogger(Foo::class.java)` to have a more idiomatic syntax. We should not abuse of top level function but this one is going to be used widely. Maybe `logger<Foo>()` ?

**Comment by sdeleuze** [comment]
Ok to integrate logging to the core, but I would let logback support as an optional module and maybe use slf4j + [spring-jcl](https://github.com/spring-projects/spring-framework/tree/master/spring-jcl) which is provided by default, sufficient for basic needs and consistent with Spring Fu goal to provide a minimal core.

**Comment by liqweed** [comment]
About the `logger<Foo>()` syntax proposal - have you considered integrating with https://github.com/MicroUtils/kotlin-logging ?

It allows to define a logger (using examples from their README):
```private val logger = KotlinLogging.logger {}```

and call the logger (slf4j under the hood) using lambdas:
```logger.debug { "Some $expensive message!" }```

**Comment by tgirard12** [comment]
Thanks for the proposal @liqweed, it seems to be a good idea, I will investigate on this too.

**Comment by sdeleuze** [comment]
@tgirard12 I don't think `LogLevel` in the `logging` module [should import logback stuff](https://github.com/spring-projects/spring-fu/blob/master/modules/logging/src/main/kotlin/org/springframework/fu/module/logging/LogLevel.kt#L19), it should not require Logback JAR to work (it brokes the CI, see https://ci.spring.io/teams/spring-fu/pipelines/spring-fu).
