### ISSUE TITLE
Is spring kofu supposed to be agnostic to paradigm being used (reactive/non-reactive)?

### ISSUE THREAD

**Issue by ssijak** [spring-projects/spring-fu#116]
I like the[ kotlin dsl](https://medium.com/@oscdj113/spring-boot-2-with-webflux-kotlin-bb1a71167591) that was introduced for the reactive web framework. But the problem was that almost all of my apps were using relational databases and using webflux with them would not be beneficial. And being that the new dsl was under the ...web.reactive package I could not use the dsl in the traditional application server.

Is spring-fu kofu supposed to create the dsl for functional app configuration and bean registration, including routes configuration, for both paradigms? If yes, that would be greatly appreciated and it seemed weird to me that it was limited at first only to reactive part of the framework.

**Comment by sdeleuze** [comment]
In theory, there is nothing preventing using Kofu with non-reactive web framework. But in practice, I am currently indeed planning to only leverage the Reactive stack for several reasons:
 - we don't have functional router for Spring MVC. This has been discussed and experimented but we are not sure yet we want to push in that direction.
 - Reactive SQL supports is just around the corner for both [Spring Framework](https://jira.spring.io/browse/SPR-16069) and Spring Data via [R2DBC](https://r2dbc.io)
- Coroutines support is going to make it possible to leverage Spring reactive stack in a more imperative way
- I don't think frameworks like Hibernate are a good fit for such kind of architecture, we will provide more lightweight à la [spring-data-jdbc](https://github.com/spring-projects/spring-data-jdbc) (a `spring-data-r2dbc` is cooking, and I will provide Coroutines API)

**Comment by sdeleuze** [comment]
I am closing this issue since I provided an answer, feel free to ask additional information if needed.
