### ISSUE TITLE
Error to cast to a FilePart

### ISSUE THREAD

**Issue by enricosecondulfo** [spring-projects/spring-fu#125]
Hi, I'm trying to implement the upload of a file with a json object using webflux. The code I use is the following: 

```
fun add(request: ServerRequest): Mono<ServerResponse> {
        return request.body(BodyExtractors.toMultipartData())
            .flatMap { parts ->
                var map: Map<String, Part> = parts.toSingleValueMap()
                var part: Part = map["image"]!! as FilePart


                ServerResponse.ok().build()
            }
    }
```

The request seems to work but when I try to cast the object to a FilePart, I get the following error:
java.lang.ClassCastException: org.springframework.http.codec.multipart.SynchronossPartHttpMessageReader$SynchronossPart cannot be cast to org.springframework.http.codec.multipart.FilePart

Can you help me, please?

Thank you

**Comment by sdeleuze** [comment]
![image](https://user-images.githubusercontent.com/141109/48954841-64f28080-ef4b-11e8-8e75-cdf457b7aeb4.png)

To be available as a `FilePart`, you need to have a `Content-disposition` header with a `filename` parameter.
