### ISSUE TITLE
Support externalized configuration (e.g. changing server.port externally)

### ISSUE THREAD

**Issue by bsideup** [spring-projects/spring-fu#138]
Hi.

It seems that properties like `ServerProperties` are simply created with constructor:
https://github.com/spring-projects/spring-fu/blob/04b317621a88c271e573c84409d89d016f4344c7/jafu/src/main/java/org/springframework/fu/jafu/web/WebFluxServerDsl.java#L51

While "classic" Spring Boot apps create them with Spring Boot's configuration system, which uses `Binder`, something like:
```java
binder.bind("server", ServerProperties.class).orElseGet(ServerProperties::new);
```

Please consider using `Binder` for them to allow externalized configuration (e.g. changing `server.port` externally)

**Comment by sdeleuze** [comment]
I would like to do that in a consistent way in Kofu and Jafu, and I need https://github.com/spring-projects/spring-boot/issues/8762 to be fixed in order to move forward on the Kofu side, so I postpone this issue to 0.0.7.

**Comment by varpa89** [comment]
I tried to deploy kofu application on heroku and came across this problem =( Is there a workaround to change port?

**Comment by sdeleuze** [comment]
For now you can use environnement variables that will be evaluated dynamicaly during startup.

**Comment by sdeleuze** [comment]
Superseded by #228 and #231.

**Comment by bsideup** [comment]
@sdeleuze still an issue, had to workaround with:
```java
app.enable(WebFluxServerDsl.webFlux(dsl -> {
    try {
        var serverPropertiesField = WebFluxServerDsl.class.getDeclaredField("serverProperties");
        serverPropertiesField.setAccessible(true);
        serverPropertiesField.set(dsl, Binder.get(app.env()).bindOrCreate("server", ServerProperties.class));
    } catch (IllegalAccessException | NoSuchFieldException e) {
        throw new RuntimeException(e);
    }
}));
```
