### ISSUE TITLE
Add support for Reactive/Coroutines SQL via R2DBC

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#14]
When available in Spring Data.

**Comment by tednology** [comment]
Is there a specific Spring Data project in the works for this that I can't find in [GitHub Spring Projects](https://github.com/spring-projects)? Or will it be rolled into an existing Spring Data module? 

Or maybe I'm asking too many questions and it's still in the planning phase! Either way - this is quite exciting.

**Comment by tednology** [comment]
I was able to unearth some more info on future support for this - for anyone curious as I there is lots of background in the Spring JIRA:

https://jira.spring.io/browse/SPR-16069

**Comment by sdeleuze** [comment]
Not yet but that's coming. Waiting that you can play with Spring Fu + https://github.com/r2dbc/r2dbc-client and send your feedback if you want ;-)

**Comment by sdeleuze** [comment]
See related https://github.com/spring-projects/spring-fu/issues/119.
