### ISSUE TITLE
Provide ability to extract CoClientResponse body

### ISSUE THREAD

**Issue by varpa89** [spring-projects/spring-fu#143]
When use CoWebClient we should have ability to parse response.
CoClientResponse has commented method
`fun <T> body(extractor: BodyExtractor<T, in ClientHttpResponse>): T
`

I created a demo project with test
https://github.com/varpa89/watchman

When call checkSpringIoHealth in HealthService I call https://spring.io/health and want to get response body

**Comment by sdeleuze** [comment]
Thanks for reporting, I will fix that for next version.

**Comment by sdeleuze** [comment]
Superseded by #128 and #150.
