### ISSUE TITLE
Provide a Kofu equivalent of @MockkBean

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#151]
Collaborate with @jnizet on a Kofu variant of `@MockkBean` from https://github.com/Ninja-Squad/springmockk (see https://github.com/spring-projects/spring-boot/issues/15749 for the context).

**Comment by sbuettner** [comment]
@sdeleuze Sure, will take a look.

We should also think about how to access mocked beans. Lets assume we call the following code in the setup part:

```
fun beforeAll() {
	    beans {
	        foo = mockkBean<Foo>
	    }
}
```

There should be a simple way to access to the `Foo` to mock the behavior in the individual tests cases.

Something like this could work:
```
val foo = mockkBean<Foo>

fun beforeAll() {
	app.customize {
	    beans {
	        mockkBean<Foo>(foo) or  useMock<Foo>(foo)
	    }
	}
}

fun test() {
...
foo.every { value } returns "customized"
...
}
```

What approach would you prefer in this case?

**Comment by sdeleuze** [comment]
I am not sure this is something we want to support, the functional variant is not a strict equivalent of the annotation based one that can do more things like resetting the mock. Here I think we want to stick with per test mock declaration to avoid side effects between tests, don't you think so?

**Comment by sbuettner** [comment]
Thinking about it, I am not sure if its good ux to launch the app and its context for every test case.

**Comment by sbuettner** [comment]
It would at least be nice to launch the the app once with all mocks in place and then model the different behaviors as part of every test. This working model (currently based on `@MockBean`) works quite well for us.

**Comment by sdeleuze** [comment]
I understand. Could you have a look if you could take inspiration of https://github.com/Ninja-Squad/springmockk to provide a functional equivalent that would reset correctly the mocks between tests?

**Comment by sdeleuze** [comment]
I am not convinced there is a need for that since the customizing capabilities bring by #44 are pretty powerful so I prefer to close this issue for now, feel free to reopen if there is some concrete PR or proposal.

**Comment by tgirard12** [comment]
The customize function work well but I think it's could be more easier to use.
A solution could be to mockk an entire configuration block like :

```
configuration { dataConfig }.mockk()

// or

enable(dataConfig.mockk())
```

I don't know if it's possible to have a list of all the beans create by a configuration
and mock them ?
