### ISSUE TITLE
Upload multipart form data with [file + json]

### ISSUE THREAD

**Issue by enricosecondulfo** [spring-projects/spring-fu#164]
I should be able to upload an image and a json.
This is the code I'm using:

   ```
 fun add(request: ServerRequest): Mono<ServerResponse> {
        return request.body(BodyExtractors.toMultipartData())
            .map { parts -> parts.toSingleValueMap() }
            .map { parts -> parts["category"] as Part }
            .flatMap { categoryPart ->

                // Flux<DataBuffer> to Category data class
                ServerResponse.ok()
                    .contentType(MediaType.APPLICATION_JSON_UTF8)
                    .body(Mono.just(Category()), classToken)
            }
    }
```
How do I convert the flux<DataBuffer> of categoryPart into a data class?

Thanks

**Comment by enricosecondulfo** [comment]
@sdeleuze Can i archive this, please?

**Comment by sdeleuze** [comment]
Hey, I am not sure to understand, are you asking me to close this issue because you have find the answer?

**Comment by enricosecondulfo** [comment]
@sdeleuze I'm sorry, I meant to say how I can solve my problem

**Comment by Sineaggi** [comment]
If you're just looking to convert a `Part` that you know contains json to a `Flux<Category>`, would this work for you?
```kotlin
import org.springframework.core.ResolvableType
import org.springframework.http.MediaType
import org.springframework.http.codec.json.Jackson2JsonDecoder

Jackson2JsonDecoder().decodeToMono(categoryPart.content(), ResolvableType.forClass(Category::class.java), MediaType.APPLICATION_JSON, mapOf())
```
Though this has less to do with spring-fu and more with spring webflux.

**Comment by sdeleuze** [comment]
I am closing this issue which is indeed not specific to Spring Fu, please ask on StackOverflow if you need more help.
