### ISSUE TITLE
Add WebTestClient facilities to the test module

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#18]
This should autoconfigure a `WebTestClient` bean when requested based on the server configuration like [`WebTestClientAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/web/reactive/WebTestClientAutoConfiguration.java) does.

**Comment by sdeleuze** [comment]
Would be useful combined with #61.

**Comment by wilkinsona** [comment]
Rather than reinventing the wheel, why not build on top of Boot where you could just make use of what `WebTestClientAutoConfiguration` already provides?

**Comment by sdeleuze** [comment]
No more test module, choice is given to use plain Junit test or SPring Boot testing facilities.
