### ISSUE TITLE
Spring KoFu Suggestions

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects/spring-fu#199]
i have some suggestons for spring kofu

1. dsl for features :  cache & scheduler & rsocket-messaging
2. dsl for webflux\rsocket-messaging request & resposne interceptor
3. support for orm relationships with r2dbc
4. support for release notes & new features (support for startup with list dependencies)
5. spring boot 2.2 is faster now, how about spring kofu in future (+ v 0.0.5)
6. optimization of dependencies to minimize jar size
7. approximation delay for production  

thanks

**Comment by sdeleuze** [comment]
Thanks for these inputs I am taking in account. RSocket support is now available, for scheduler there is already an issue, for orm relationships with r2dbc please reach Spring Data team, see #201 for the roadmap, I will share more info when possible.

**Comment by halimpuckjava** [comment]
thanks
