### ISSUE TITLE
Add support for Spring Data Redis

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#203]
Both blocking and Reactive

**Comment by ciferkey** [comment]
To clarify this issue's goal (and #202 / #204) is the idea to implement a kofu DSL similar to ReactiveMongoDsl?

**Comment by sdeleuze** [comment]
The idea is to provide a Kofu DSL to configure the functional part of Spring Data Redis (equivalent of Spring Boot auto-configuration).

**Comment by wpanas** [comment]
Hi, I have made a really good progress with this feature. In a few days, I will make PR :)

**Comment by sdeleuze** [comment]
Superseeded by #230.
