### ISSUE TITLE
It's possible to defined a generic bean using Kotlin Bean Definition DSL?

### ISSUE THREAD

**Issue by guitcastro** [spring-projects/spring-fu#205]
I am using Kotlin Bean Definition DSL and I want to define a generic bean, like `Foo<T>`, in Java this can be done by defining `T` in the method. However, in the DSL syntax, this is not possible.

It's possible to define a generic bean using Bean Definition DSL? 
If not, what are the challenges of implementing this?

**Comment by sdeleuze** [comment]
Could you please share the Java code that you would like to convert to the Kotlin + DSL syntax ?

**Comment by sdeleuze** [comment]
@guitcastro Any chance to have the Java version?

**Comment by sdeleuze** [comment]
I close this issue since no answer.
