### ISSUE TITLE
Spring Kofu 0.1-build & MongoReactiveRepository issue

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects/spring-fu#214]
hi

1. i try to use reactiveMongodb with ReactiveFluentMongoOperations (injected normaly in my repository) its work fine however with ReactiveMongoRepository injection issue (this interface must be declare in beans dsl !!!) 
2.  
```

data class Patient(@Id val id: Int,
                   var fisrtName: String,
                   var lastName: String,
                   var age: Int? = null,
                   var adress: String? = null)

class PatientRespository(val mongo: ReactiveFluentMongoOperations) {
    suspend fun update(patient: Patient) = mongo.update<Patient>().replaceWith(patient).asType<Patient>().findReplaceAndAwait()
}

Caused by: com.mongodb.MongoCommandException: Command failed with error 66 (ImmutableField): 'After applying the update, the (immutable) field '_id' was found to have been altered to _id: xxx'
 ```
exception when using ReactiveFluentMongoOperations to update patient entity

3.  findReplaceAndAwait() method in ReactiveFluentMongoOperations  always return the old entity from database

**Comment by sdeleuze** [comment]
Hi

1. Repositories are not supported for now, and I am not sure yet they should be supported with this functional approach. For the time being I will improve the documentation.

2. i don't think this is related to Kofu

3. Surprised given the definition of the extension, see https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/main/kotlin/org/springframework/data/mongodb/core/ReactiveUpdateOperationExtensions.kt#L67. In any case this is not related to Kofu.

**Comment by halimpuckjava** [comment]
thanks
