### ISSUE TITLE
java 8 time issue serialization

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects/spring-fu#227]
hi

how to serialize java 8 time (LocalTime) with jackson dsl

**Comment by sdeleuze** [comment]
Java 8 date/time API support should be configured by default by  the underneath `Jackson2ObjectMapperBuilder`, if that's not the case please provide a repro project.

**Comment by halimpuckjava** [comment]
thanks

how use Jackson2ObjectMapperBuilder in kofu jackson dsl ??
