### ISSUE TITLE
Jafu samples

### ISSUE THREAD

**Issue by jabrena** [spring-projects/spring-fu#240]
Hi @sdeleuze, 

I was checking the readme about the project, but I noticed that I didn't see any explicit information about **Jafu**. Indeed, i didn't see examples in samples folder.

Why?

Many thanks in advance

Juan Antonio

Related link:
https://spring.io/blog/2018/10/02/the-evolution-of-spring-fu

**Comment by sdeleuze** [comment]
You will find more information here: https://github.com/spring-projects/spring-fu/issues/201.
