### ISSUE TITLE
Allow to customize an existing application (for tests, mocking, etc.)

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#44]
Maybe using https://github.com/mockk/mockk.

**Comment by oleksiyp** [comment]
Added a ticket https://github.com/mockk/mockk/issues/118

**Comment by sdeleuze** [comment]
I finally had some times to play with Mockk, and it is now clear to me that it is what we should promote on Spring side to Mock beans in Spring applications written in Kotlin. @jnizet has created a nice `@MockBean` like support for Mockk with its [springmockk](https://github.com/Ninja-Squad/springmockk), it will [not be integrated for now in Spring Boot](https://github.com/spring-projects/spring-boot/issues/15749) even if there is a big demand for that because current infra is sadly Mockito specific. But we can move forward on Spring Fu side by thinking what is missing for such first class support.

I think @sbuettner proposal about allowing to customize an existing application is interesting, and would be useful for other use case than mocking. We could maybe support something like as a first step:

```
fun beforeAll() {
  app.beans {
    bean { mock<Foo>(isPrimary = true)  }
    bean { mock<Bar>(isPrimary = true).every { ... } }
  }.run(profiles = "test")
}
```
Then as a second step (with another dedicated issue) we could provide a functional Mockk equivalent to `@MockBean` like `beans { mockBean<Foo>() }`.

Any thoughts?

**Comment by oleksiyp** [comment]
Syntax looks good to me. Mockk was designed to have few front facing DSLs via so called Gateway API

**Comment by sdeleuze** [comment]
It turned out to be quite easy and powerful since we now can customize an existing app with any DSL in an additive configuration mode, only `beans { }` have the `isPrimary = true` capability for now.

```
val app = application {
    beans {
        bean { Bar("original") }
    }
}
app.customize {
    beans {
        bean(isPrimary = true) {
            mockk<Bar>().apply {
                every { value } returns "customized"
            }
    }
}
```

**Comment by sbuettner** [comment]
@sdeleuze I like your approach as it uses the default infra to register mocks. 

I could still see an extension method inside the `beans {}` context like `mockk<Foo> {...}` that internally calls `bean(isPrimary = true)` as this seems the be the main usage. A scenario where a mocked bean should not be registered as the primary one seems to be exception. As `isPrimary` in this case would have the default value of `true` one can always override it with false.

**Comment by sdeleuze** [comment]
Since for now we recreate context every time with no specific caching involved, we can indeed maybe provide a simple `mockkBean` alias without having to invloved all the `@MockkBean` infrastructure. Let's discuss that as part of #151.
