### ISSUE TITLE
Reuse Spring Boot configuration classes in a functional way

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-fu#54]
If we're willing to interoperate w/ configuration annotations then we could change the default `ApplicationContext` instance to `AnnotationConfigApplicationContext` and hat would allow `bean<FooConfig>()` to work out of the box. but that would also require reflection and annotations and other things that frustrate tools like Graal. 

If we don't want annotations then we could possibly register modules which then register beans which e arrive at by manually invoking methods in existing java config classes? 

Or we could somehow automatically generate functional config from Java configuration classes.

**Comment by sdeleuze** [comment]
To be discussed with @wilkinsona.

**Comment by sdeleuze** [comment]
As proposed by @wilkinsona, we should try to do like @dsyer [did](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/ContextFunctionCatalogInitializer.java#L60), ie  using a `BeanDefinitionRegistryPostProcessor` which is particularly interesting as it’s called after all of a user’s own configuration has been processed.

**Comment by sdeleuze** [comment]
I think https://github.com/dsyer/spring-boot-auto-reflect approach could be interesting to try. We could maybe even generate automatically functional configurations based on Boot JavaConfig one as part of Spring Fu build process and not do that at runtime.

**Comment by sdeleuze** [comment]
See also https://github.com/dsyer/spring-init-experiment.

**Comment by sdeleuze** [comment]
There will be some polish and refactoring especially for conditions but Kofu configuration now leverage Spring Boot auto-configuration in a functional way. Thanks for your help @dsyer, @bclozel and @wilkinsona.
