### ISSUE TITLE
Explore JUnit 5 integration

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#61]
Currently, Spring Fu applications are tested mainly in 2 ways:
 - Unit tests for individual classes is made easy by generalized constructor injection usage, potentially with Mocking, without `ApplicationContext` being involved (we need to add examples of that as part of #44).
 - Integration tests by just running the application, eventually with a specified profile like [in this example](https://github.com/spring-projects/spring-fu/blob/master/samples/reactive-webapp/src/test/kotlin/org/springframework/fu/sample/reactive/IntegrationTests.kt).

Even if Spring Fu is designed to be testable with not specific support, we should explore if JUnit 5 integration makes sense.

@sbrannen Since Spring Fu is heavily based on `ApplicationContextInitializer`, is there something already supported in `SpringExtension` we could leverage to register beans on the context and take advantage of test classes `@Autowired` support for example?

**Comment by wilkinsona** [comment]
> to register beans on the context and take advantage of test classes @Autowired support for example

If Spring Fu built on top of Boot, which I think it should, you'd benefit from the change that's currently proposed in https://github.com/spring-projects/spring-boot/issues/8115#issuecomment-396920841. Note the custom `BeanDefinitionLoader` in the repository that @dsyer links to in his comment.

**Comment by sbrannen** [comment]
> Since Spring Fu is heavily based on `ApplicationContextInitializer`, is there something already supported in `SpringExtension` we could leverage to register beans on the context and take advantage of test classes `@Autowired` support for example?

Sure, there are two major options here.

You can register an `ApplicationContextInitializer` via `@ContextConfiguration(initializers = ...)`.

You can make use of an auto-detected `ContextCustomizer`. That's actually what Spring Boot Test does, and it was the original PR from @philwebb that got that into the _Spring TestContext Framework_.

Using an `ApplicationContextInitializer` would typically require that the end user register it explicitly for each test class; whereas, an `ContextCustomizer` can be registered automatically by the Spring Fu framework.

These features are of course not specific to JUnit Jupiter. Only the support for constructor and method injection of such beans would be specific to the `SpringExtension`.

Does one of those options work for you?

**Comment by sdeleuze** [comment]
Thanks for your feedback @wilkinsona and @sbrannen, we are going to try to leverage Boot for that indeed.

**Comment by sdeleuze** [comment]
Typical Spring Fu tests are just plain JUnit 5 tests + Spring Fu is now based on Boot so I close this issue.
