### ISSUE TITLE
Serve static website

### ISSUE THREAD

**Issue by jabrena** [spring-projects/spring-fu#66]
Hi,

I would like to know if `Spring-fu` is able to serve static websites.

Many thanks in advance.

Cheers

Juan Antonio

**Comment by sdeleuze** [comment]
This is now fixed, and can be configured [like that](https://github.com/spring-projects/spring-fu/blob/13862a10cbcaa66c19d31bb6b4f922a1cbeb14a5/samples/minimal-webapp/src/main/kotlin/org/springframework/fu/sample/minimal/Application.kt#L31).
