### ISSUE TITLE
Only display a log message without stacktrace for catch exceptions

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#76]
Stacktraces just add noise in that case.

**Comment by sdeleuze** [comment]
Should leverage Spring Boot for that, need to see if current exception handling with meaningful messages + @rstoyanchev log improvements are enough or if there is remaining work to be done.

**Comment by rstoyanchev** [comment]
There were changes in WebFlux that should make a difference. The general rule is that only exceptions that remain unhandled are logged with a stacktrace (at error level). For handled exceptions, the `ResponseStatusExceptionHandler`  has a warn logger that needs to be enabled explicitly to show exception details. We can refine further from here but it should be a lot better. 

Keep in mind also [a few refinements](https://github.com/spring-projects/spring-boot/issues/13511#issuecomment-398859407) I suggested on the Boot side as well.

**Comment by sdeleuze** [comment]
Closing this issue after the improvements made on Framework side, and Kotlin configuration should be a flavor of Boot so no need something specific here.
