### ISSUE TITLE
Validation data class in functional way

### ISSUE THREAD

**Issue by enricosecondulfo** [spring-projects/spring-fu#83]
Hello guys,
i'm very enthusiastic about project. Is under development the possibility of validate a data class in functional way?

Thanks for the good job

**Comment by sdeleuze** [comment]
Hey, glad you like Spring Fu. You can currently validate programaticaly data classes but we do not provide yet any specific feature about functional validation. Could you please detail what you have in mind?

**Comment by mykolapolonskyi** [comment]
hi there - I found this issue in mailing list. I think you will be interesting in this blog post 
https://blog.sourced-bvba.be/article/2018/01/13/kotlin-validation/
p.s. I don't know how exactly usage of Hibernate validations correlate with SpringFu goals - but dsl from blog looks very good for end usage and seems to be in same style as SpringFu configurations

**Comment by enricosecondulfo** [comment]
@mykolapolonskyi The question arises exactly from the article you mentioned. That's why I asked if there was a stardard to be adopted in functional development.

**Comment by sdeleuze** [comment]
I will give that some thoughts. See also related https://github.com/cdimascio/swagger-spring-functional/blob/master/README.md project.

**Comment by sdeleuze** [comment]
Could people interested in this issue have a look to https://github.com/making/yavi and see if it can help here? cc @making

**Comment by making** [comment]
Here is a sample project
https://github.com/making/demo-spring-fu-yavi
Please take a look if you are interested

**Comment by enricosecondulfo** [comment]
@making your library is so beautiful but is there a solution to validate data class based on some conditions. For example i would like to check if field text has a length less than or equal to 10 only in case of update.
Thanks

**Comment by making** [comment]
@enricosecondulfo Thanks for your feedback. I filed an issue about that on my repo
https://github.com/making/yavi/issues/2

**Comment by sdeleuze** [comment]
@making Any chance you could send a PR to update samples to leverage Yavi, maybe by adding a `POST` request handling?

**Comment by making** [comment]
@sdeleuze just sent a PR. 
I've added new samples for simplicity.
