### ISSUE TITLE
Make the application DSL more intuitive

### ISSUE THREAD

**Issue by apatrida** [spring-projects/spring-fu#84]
As a new person seeing this for the first time, I find the DSL feels like a bunch of random words put together without knowing their purpose.  It is all nouns and no verbs.  

Maybe it would be good to make a usability study of such an important part of the framework by observing new developers interpreting what they see when they drop into the samples or try to write their first app.  Before this gets too baked and hard to change later.

If you know Spring / Spring Boot maybe it is already making sense, otherwise it feels "off"

**Comment by AlexCzar** [comment]
Most of it is declarative configuration, for which nouns are generally okay. Being similar to Spring Boot is an intended design choice, I think.
Do you have any specific suggestions, what can be improved?

**Comment by apatrida** [comment]
I don't know it well enough to make suggestions, so I'm just providing my reaction that it isn't self-evident when reading it for the first time.

**Comment by sdeleuze** [comment]
I also think nouns are ok for such declarative approach, and the name are referring to the underlying used Spring elements. We have also a dedicated documentation improvement topic to come. I close this issue for now since I am not sure what to do exactly here.

**Comment by sdeleuze** [comment]
FYI, I have removed the `webflux { }` top level block in favor of top level `client { }` and `server { }` ones, and grouped all the beans in a `beans { }` in order to keep the same semantics than raw Spring Framework.
