### ISSUE TITLE
Text and Resource codecs should be configured explicitly

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-fu#88]
To avoid a feature sometimes perceived by users as a bug, see [SPR-17080](https://jira.spring.io/browse/SPR-17080) and [SPR-15842](https://jira.spring.io/browse/SPR-15842). 

These [preconfigured codecs](https://github.com/spring-projects/spring-fu/blob/master/modules/webflux/src/main/kotlin/org/springframework/fu/module/webflux/WebFluxModule.kt#L78-L80) should be replaced by `WebFluxCodecsModule` member functions.

**Comment by ciferkey** [comment]
Should the same change also be mirrored in the [WebFluxClientModule](https://github.com/spring-projects/spring-fu/blob/master/modules/webflux/src/main/kotlin/org/springframework/fu/module/webflux/WebFluxModule.kt#L146-L148)?

**Comment by matoatoa** [comment]
I started with some refactoring see https://github.com/spring-projects/spring-fu/pull/92

**Comment by sdeleuze** [comment]
@matoatoa Thanks for your help. I chose to create by default `String` and `Resource` codecs when no `codecs { }` block is defined, and configure no default codecs when there is ssuch block defined. Is it fine for you?

@ciferkey I did the same for the client and server
