### ISSUE TITLE
Missing maven repository and wrong import for Bootstrap application

### ISSUE THREAD

**Issue by wilder** [spring-projects/spring-fu#89]
Hello, I tried to start a new spring-fu coroutine project using the [bootstrap project](https://github.com/spring-projects/spring-fu/blob/master/samples/coroutine-webapp/) but I've found some problems:

The first problem was that it couldn't find the spring-fu dependency:
```
org.gradle.api.GradleException: Failed to resolve imported Maven boms: Could not find org.springframework.fu:spring-fu-dependencies:0.0.1.BUILD-SNAPSHOT.
Searched in the following locations:
...
```

I could solve it by adding spring's snapshot repository to the [build.gradle.kts](https://github.com/spring-projects/spring-fu/blob/master/bootstraps/coroutine-webapp/build.gradle.kts) file
```
repositories {
   ...
   maven("https://repo.spring.io/snapshot")
   ...
```

The other problem was after compiling the project, the ```coRouter``` couldn't be resolved at [Application.kt](https://github.com/spring-projects/spring-fu/blob/master/bootstraps/coroutine-webapp/src/main/kotlin/com/example/Application.kt) because it was using the following import:
```
import org.springframework.fu.module.webflux.coroutine.coroutineRoutes
```

I fixed it by changing it to:
```
import org.springframework.fu.module.webflux.coroutine.coRouter
```

Is this the expected behavior? 
May I do a pull request with those changes?

**Comment by sdeleuze** [comment]
It is now fixed and checked by the CI for avoiding such issue in the future, thanks for reporting.
